name: page_build

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: actions/jekyll-build-pages@v1
        with:
          destination: "./output"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./output"
